version:  0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - gradle clean package
  post_build:
    commands:
      - echo Build completed successfully
artiacts:
  files:
    - gradle/wrapper/gradle-wrapper.jar
  discard-paths: yes
